# Performed Data Cleaning

In [19]:
import pandas as pd
import pathlib


# Load the dataset
DATA_PATH: pathlib.Path = pathlib.Path("C:/Ahsan.docx/PROJECT/MetroPT_project/MetroPT/dataset_train.csv")
df: pd.DataFrame = pd.read_csv(DATA_PATH)
df.head(10)

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,...,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality
0,2022-01-01 06:00:00,-0.012,9.758,9.760,-0.028,1.576,63.350,19.049625,3.9550,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
1,2022-01-01 06:00:01,-0.012,9.760,9.760,-0.028,1.578,63.250,19.049625,4.0275,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
2,2022-01-01 06:00:02,-0.010,9.760,9.760,-0.028,1.578,63.325,19.040281,3.9450,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
3,2022-01-01 06:00:03,-0.012,9.756,9.756,-0.030,1.576,63.200,19.040281,3.9300,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
4,2022-01-01 06:00:04,-0.012,9.756,9.756,-0.030,1.578,63.150,19.049625,3.9950,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
5,2022-01-01 06:00:05,-0.012,9.754,9.754,-0.030,1.576,63.075,19.049625,3.9950,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
6,2022-01-01 06:00:06,-0.012,9.754,9.754,-0.028,1.578,63.000,19.049625,3.9475,1,...,1,1,0,0,0,0,-8.65935,41.2124,0,1
7,2022-01-01 06:00:07,-0.010,9.752,9.754,-0.028,1.576,63.075,19.040281,4.0225,1,...,1,1,0,0,0,0,-8.65935,41.2124,0,1
8,2022-01-01 06:00:08,-0.012,9.752,9.752,-0.028,1.576,63.075,19.049625,3.9525,1,...,1,1,0,0,0,0,-8.65935,41.2124,0,1
9,2022-01-01 06:00:09,-0.010,9.750,9.750,-0.028,1.576,63.000,19.049625,3.9250,1,...,1,1,0,0,0,0,-8.65935,41.2124,0,1

In [20]:
df.describe()

,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality
count,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,10773588.0,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07
mean,1.152184e+00,8.974608e+00,7.751421e+00,-2.454095e-02,1.565051e+00,6.730720e+01,2.039515e+01,2.383179e+00,8.698926e-01,1.301137e-01,9.347704e-01,8.698921e-01,6.281380e-03,0.0,2.784588e-07,1.488919e-03,-4.384534e+00,2.091144e+01,4.913657e+00,5.076832e-01
std,3.075296e+00,7.006960e-01,3.051447e+00,1.486569e-01,9.016339e-02,5.383852e+00,3.743607e+00,2.193381e+00,3.364215e-01,3.364285e-01,2.469306e-01,3.364221e-01,7.900585e-02,0.0,5.276919e-04,3.855778e-02,4.317794e+00,2.059254e+01,1.151822e+01,4.999410e-01
min,-3.000000e-02,6.000000e-03,-3.400000e-02,-3.800000e-02,1.350000e+00,1.387500e+01,1.883472e+01,-1.250000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,-9.130040e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,-8.000000e-03,8.484000e+00,8.232000e+00,-3.200000e-02,1.470000e+00,6.367500e+01,1.901225e+01,2.500000e-03,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,-8.658910e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,-8.000000e-03,8.984000e+00,8.746000e+00,-2.800000e-02,1.590000e+00,6.832500e+01,1.904028e+01,3.705000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,-8.542650e+00,4.115190e+01,0.000000e+00,1.000000e+00
75%,-6.000000e-03,9.492000e+00,9.290000e+00,-2.600000e-02,1.638000e+00,7.107500e+01,1.925519e+01,3.837500e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,4.118820e+01,0.000000e+00,1.000000e+00
max,1.087600e+01,1.040800e+01,1.041400e+01,8.326000e+00,2.054000e+00,9.790000e+01,4.307241e+01,9.685000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.0,1.000000e+00,1.000000e+00,0.000000e+00,4.194900e+01,3.230000e+02,1.000000e+00

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10773588 entries, 0 to 10773587
Data columns (total 21 columns):
 #   Column           Dtype
---  ------           -----
 0   timestamp        object
 1   TP2              float64
 2   TP3              float64
 3   H1               float64
 4   DV_pressure      float64
 5   Reservoirs       float64
 6   Oil_temperature  float64
 7   Flowmeter        float64
 8   Motor_current    float64
 9   COMP             int64
 10  DV_eletric       int64
 11  Towers           int64
 12  MPG              int64
 13  LPS              int64
 14  Pressure_switch  int64
 15  Oil_level        int64
 16  Caudal_impulses  int64
 17  gpsLong          float64
 18  gpsLat           float64
 19  gpsSpeed         int64
 20  gpsQuality       int64
dtypes: float64(10), int64(10), object(1)
memory usage: 1.7+ GB

In [22]:
df_processed: pd.DataFrame = df.drop(columns=["Pressure_switch", "gpsLat", "gpsLong", "gpsQuality"])\
    .astype({
        "timestamp" : "datetime64",
        "TP2" : "float16",
        "TP3" : "float16",
        "H1"  : "float16",
        "DV_pressure" : "float16",
        "Reservoirs" : "float16",
        "Oil_temperature" : "float16",
        "Flowmeter" : "float16",
        "Motor_current" : "float16",
        "COMP" : "int16",
        "DV_eletric" : "int16",
        "Towers" : "int16",
        "MPG" : "int16",
        "LPS" : "int16",
        "Oil_level" : "int16",
        "Caudal_impulses" : "int16",
        "gpsSpeed" : "int16",   
    })

In [23]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10773588 entries, 0 to 10773587
Data columns (total 17 columns):
 #   Column           Dtype
---  ------           -----
 0   timestamp        datetime64[ns]
 1   TP2              float16
 2   TP3              float16
 3   H1               float16
 4   DV_pressure      float16
 5   Reservoirs       float16
 6   Oil_temperature  float16
 7   Flowmeter        float16
 8   Motor_current    float16
 9   COMP             int16
 10  DV_eletric       int16
 11  Towers           int16
 12  MPG              int16
 13  LPS              int16
 14  Oil_level        int16
 15  Caudal_impulses  int16
 16  gpsSpeed         int16
dtypes: datetime64[ns](1), float16(8), int16(8)
memory usage: 411.0 MB

In [4]:
import pandas as pd
# Load the Excel file
file_path ="aggregated_dataset.csv"
df: pd.DataFrame = pd.read_csv(file_path)
df.head(10)

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,...,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality
0,2022-01-01 06:00:00,-0.010767,9.729667,9.730600,-0.028033,1.576167,62.407500,1142.828000,3.963792,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659349,41.212328,0.000000,1.0
1,2022-01-01 06:01:00,-0.010533,9.670433,9.670500,-0.028233,1.574900,61.358333,1142.865375,3.957583,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659353,41.212300,0.083333,1.0
2,2022-01-01 06:02:00,-0.010600,9.612667,9.612733,-0.028333,1.573633,61.129583,1142.865375,3.959542,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659369,41.212300,0.000000,1.0
3,2022-01-01 06:03:00,-0.010267,9.555100,9.555133,-0.028300,1.572633,61.028333,1142.856031,3.956625,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659370,41.212300,0.033333,1.0
4,2022-01-01 06:04:00,-0.009967,9.496500,9.496167,-0.028367,1.572000,61.515000,1142.846687,1.204333,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659384,41.212300,0.000000,1.0
5,2022-01-01 06:05:00,-0.010267,9.433300,9.432167,-0.028867,1.571800,60.325833,1142.865375,0.007375,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659394,41.212268,0.000000,1.0
6,2022-01-01 06:06:00,-0.010300,9.368833,9.368267,-0.028867,1.572000,58.381250,1142.846687,0.007500,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659382,41.212200,0.000000,1.0
7,2022-01-01 06:07:00,-0.010433,9.303467,9.303767,-0.029067,1.572200,56.797500,1142.005750,0.007500,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659391,41.212213,0.000000,1.0
8,2022-01-01 06:08:00,-0.010700,9.239367,9.239067,-0.028967,1.572767,55.771250,1139.473594,0.007458,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659380,41.212300,0.000000,1.0
9,2022-01-01 06:09:00,-0.010933,9.173833,9.174000,-0.028933,1.573400,55.137083,1136.577031,0.007500,1.0,...,60,1.0,0.0,0.0,0.0,0,-8.659384,41.212300,0.000000,1.0

In [5]:
df.describe()

,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality
count,179709.000000,179709.000000,179709.000000,179709.000000,179709.000000,179709.000000,219470.000000,179709.000000,179709.000000,179709.000000,219470.000000,179709.000000,179709.000000,179709.0,1.797090e+05,219470.000000,179709.000000,179709.000000,179709.000000,179709.000000
mean,1.152142,8.974573,7.751401,-0.024544,1.565053,67.307652,1001.179993,2.383212,0.932151,0.192539,45.887051,0.869890,0.006289,0.0,2.782276e-07,0.073090,-4.384485,20.911199,4.913999,0.532522
std,2.770003,0.687375,2.761500,0.024439,0.090154,5.330722,504.050137,2.082315,0.251487,0.394295,23.846544,0.303528,0.077832,0.0,1.179465e-04,1.870523,4.238055,20.209539,9.476214,0.498943
min,-0.024000,0.007433,-0.026000,-0.036333,1.366233,15.506250,0.000000,-0.007667,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,0.000000,-8.693834,0.000000,0.000000,0.000000
25%,-0.008367,8.484200,8.187733,-0.032133,1.469800,63.719167,1131.531406,0.004083,1.000000,0.000000,39.000000,1.000000,0.000000,0.0,0.000000e+00,0.000000,-8.658740,0.000000,0.000000,0.000000
50%,-0.006933,8.983667,8.697400,-0.027867,1.590400,68.326667,1141.902969,3.707875,1.000000,0.000000,60.000000,1.000000,0.000000,0.0,0.000000e+00,0.000000,-5.744037,27.441332,0.000000,1.000000
75%,-0.004467,9.491667,9.228500,-0.026033,1.638233,71.038750,1155.087000,3.829333,1.000000,0.000000,60.000000,1.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000,41.188177,5.183333,1.000000
max,10.544000,10.248467,10.249833,0.189500,1.946900,97.722083,2136.395656,6.330000,1.000000,1.000000,60.000000,1.000000,1.000000,0.0,5.000000e-02,60.000000,0.000000,41.271600,78.333333,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219470 entries, 0 to 219469
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   timestamp        219470 non-null  object
 1   TP2              179709 non-null  float64
 2   TP3              179709 non-null  float64
 3   H1               179709 non-null  float64
 4   DV_pressure      179709 non-null  float64
 5   Reservoirs       179709 non-null  float64
 6   Oil_temperature  179709 non-null  float64
 7   Flowmeter        219470 non-null  float64
 8   Motor_current    179709 non-null  float64
 9   COMP             179709 non-null  float64
 10  DV_eletric       179709 non-null  float64
 11  Towers           219470 non-null  int64
 12  MPG              179709 non-null  float64
 13  LPS              179709 non-null  float64
 14  Pressure_switch  179709 non-null  float64
 15  Oil_level        179709 non-null  float64
 16  Caudal_impulses  219470 non-null  int64
 17  gpsLong          179709 non-null  float64
 18  gpsLat           179709 non-null  float64
 19  gpsSpeed         179709 non-null  float64
 20  gpsQuality       179709 non-null  float64
dtypes: float64(18), int64(2), object(1)
memory usage: 35.2+ MB

In [33]:
df_processed: pd.DataFrame = df.drop(columns=["Pressure_switch", "gpsLat", "gpsLong", "gpsQuality"])\
    .astype({
        "timestamp" : "datetime64",
        "TP2" : "float16",
        "TP3" : "float16",
        "H1"  : "float16",
        "DV_pressure" : "float16",
        "Reservoirs" : "float16",
        "Oil_temperature" : "float16",
        "Flowmeter" : "float16",
        "Motor_current" : "float16",
        "COMP" : "bool",
        "DV_eletric" : "bool",
        "Towers" : "bool",
        "MPG" : "bool",
        "LPS" : "bool",
        "Oil_level" : "bool",
        "Caudal_impulses" : "bool",
        "gpsSpeed" : "int16",   
    })

In [34]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10773588 entries, 0 to 10773587
Data columns (total 17 columns):
 #   Column           Dtype
---  ------           -----
 0   timestamp        datetime64[ns]
 1   TP2              float16
 2   TP3              float16
 3   H1               float16
 4   DV_pressure      float16
 5   Reservoirs       float16
 6   Oil_temperature  float16
 7   Flowmeter        float16
 8   Motor_current    float16
 9   COMP             bool
 10  DV_eletric       bool
 11  Towers           bool
 12  MPG              bool
 13  LPS              bool
 14  Oil_level        bool
 15  Caudal_impulses  bool
 16  gpsSpeed         int16
dtypes: bool(7), datetime64[ns](1), float16(8), int16(1)
memory usage: 339.1 MB

In [31]:
!pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-19.0.0-cp39-cp39-win_amd64.whl.metadata (3.4 kB)
Downloading pyarrow-19.0.0-cp39-cp39-win_amd64.whl (25.5 MB)
   ---------------------------------------- 25.5/25.5 MB 25.2 MB/s eta 0:00:00

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Installing collected packages: pyarrow
Successfully installed pyarrow-19.0.0

In [35]:
from pyarrow import feather
OUT_PATH: pathlib.Path = pathlib.Path("C:/Ahsan.docx/PROJECT/MetroPT_project/MetroPT/")
df_processed.to_feather(OUT_PATH / "Processed.feather")